// src/app/terms/page.tsx
"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { useRouter } from 'next/navigation';
import Header from '@/components/ui/header';
import Link from 'next/link';

export default function TermsOfServicePage() {
    const router = useRouter();

    return (
        <div className="min-h-screen flex flex-col items-center bg-background text-foreground">
            <Header title="Terms of Service" />
            <main className="container mx-auto py-8 max-w-3xl flex-grow">
                <div className="flex items-center gap-4 mb-8">
                    <Button variant="ghost" size="icon" onClick={() => router.back()} aria-label="Go back">
                        <ArrowLeft className="h-5 w-5" />
                    </Button>
                    <h1 className="text-3xl font-bold text-primary">Terms of Service</h1>
                </div>

                <Card>
                    <CardHeader>
                        <CardTitle className="text-2xl">Terms of Service</CardTitle>
                        <CardDescription>Last updated: {new Date().toLocaleDateString()}</CardDescription>
                    </CardHeader>
                    <CardContent className="prose dark:prose-invert max-w-none">
                        <h3>1. Acceptance of Terms</h3>
                        <p>By accessing and using Daily Grace ("the App"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this App.</p>
                        
                        <h3>2. User Conduct</h3>
                        <p>You agree to use the App only for lawful purposes. You are prohibited from posting on or transmitting through the App any material that is harmful, threatening, abusive, defamatory, or obscene.</p>

                        <h3>3. Account Responsibility</h3>
                        <p>You are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer. You agree to accept responsibility for all activities that occur under your account or password.</p>
                        
                        <h3>4. Intellectual Property</h3>
                        <p>The App and its original content (excluding content provided by users or generated by AI based on user input), features, and functionality are and will remain the exclusive property of Daily Grace and its licensors. AI-generated content based on public domain works (like the Bible) is for personal use within the App.</p>

                        <h3>5. Termination</h3>
                        <p>We may terminate or suspend your account and bar access to the App immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.</p>

                        <h3>6. Limitation of Liability</h3>
                        <p>In no event shall Daily Grace, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the App.</p>

                        <h3>7. Changes to Terms</h3>
                        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide at least 30 days' notice prior to any new terms taking effect. By continuing to access or use our App after those revisions become effective, you agree to be bound by the revised terms.</p>
                    </CardContent>
                </Card>
            </main>
             <footer className="w-full text-center py-6 px-4 border-t border-border/60">
                <p className="text-sm text-muted-foreground">&copy; {new Date().getFullYear()} Daily Grace.</p>
            </footer>
        </div>
    );
}
